// <auto-generated />
using System;
using FamilyBudget.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyBudget.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyBudget.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepeatDay")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 12, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2343),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2381),
                            RepeatDay = 0,
                            Value = 572m
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 12, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2393),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2395),
                            RepeatDay = 0,
                            Value = -852m
                        },
                        new
                        {
                            Id = 3,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 12, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2399),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2402),
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 11, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2405),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2407),
                            RepeatDay = 0,
                            Value = 606m
                        },
                        new
                        {
                            Id = 5,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 11, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2410),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2412),
                            RepeatDay = 0,
                            Value = -495m
                        },
                        new
                        {
                            Id = 6,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 11, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2416),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2418),
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 10, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2421),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2423),
                            RepeatDay = 0,
                            Value = 476m
                        },
                        new
                        {
                            Id = 8,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 10, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2426),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2428),
                            RepeatDay = 0,
                            Value = -169m
                        },
                        new
                        {
                            Id = 9,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 10, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2430),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2432),
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 9, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2436),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2438),
                            RepeatDay = 0,
                            Value = 612m
                        },
                        new
                        {
                            Id = 11,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 9, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2440),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2442),
                            RepeatDay = 0,
                            Value = -499m
                        },
                        new
                        {
                            Id = 12,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 9, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2445),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2447),
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 8, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2449),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2451),
                            RepeatDay = 0,
                            Value = 839m
                        },
                        new
                        {
                            Id = 14,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 8, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2454),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2456),
                            RepeatDay = 0,
                            Value = -298m
                        },
                        new
                        {
                            Id = 15,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 8, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2458),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2460),
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 7, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2506),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2508),
                            RepeatDay = 0,
                            Value = 636m
                        },
                        new
                        {
                            Id = 17,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 7, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2511),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2513),
                            RepeatDay = 0,
                            Value = -528m
                        },
                        new
                        {
                            Id = 18,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 7, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2517),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2519),
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Health",
                            CreatedTime = new DateTime(2023, 5, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2523),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 9, 3, 59, 45, 698, DateTimeKind.Local).AddTicks(2525),
                            RepeatDay = 14,
                            Value = -55m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
